In [13]:
import statistics as stat
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
import pandas as pd
import statsmodels.api as sn
np.random.seed(0)


In [14]:
df=pd.read_csv('IMDB Dataset.csv')

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()
docs=np.array(['The sun is shining ', 
' The weather is sweet', 
' The sun is shining and the weather is sweet, and one and one is two ' ])
bag=count.fit_transform(docs)

In [16]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [17]:
print(bag.toarray()) 

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [3 3 2 1 1 1 2 1 1]]


In [18]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer()
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs).toarray()))


  (0, 6)	0.4337078595086741
  (0, 4)	0.5584778353707552
  (0, 3)	0.5584778353707552
  (0, 1)	0.4337078595086741
  (1, 8)	0.5584778353707552
  (1, 6)	0.4337078595086741
  (1, 5)	0.5584778353707552
  (1, 1)	0.4337078595086741
  (2, 8)	0.16656281522373023
  (2, 7)	0.219010085653535
  (2, 6)	0.258701769306441
  (2, 5)	0.16656281522373023
  (2, 4)	0.16656281522373023
  (2, 3)	0.16656281522373023
  (2, 2)	0.43802017130707
  (2, 1)	0.38805265395966154
  (2, 0)	0.657030256960605
